name: localhost/build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy (localhost)
        run: |
          make deploy DOCKER_COMPOSE_ARGS=-d
          make healthcheck ENV=localhost
